src/WebApp/Controllers/GraphController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class GraphController : Controller
    {
        private readonly ILogger<GraphController> _logger;

        public GraphController(ILogger<GraphController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

src/WebApp/Views/Graph/Index.cshtml
@{
    ViewData["Title"] = "Create new graph";
    ViewData["GoogleId"] = "bD3OaRNT6jAm17sCw77qwXlM9ges1tpaV7T_b-B0m2Q";
    ViewData["Description"] = "GraphCreator allows you to create, edit and experiment with discrete mathematical graphs. ";
}
<head>
    <link rel="stylesheet" href="~/css/graphPage.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/graph.css" asp-append-version="true" />
    <script src="~/js/d3.v7.js"></script>
    <script type="module" src="~/js/graphWorker.js"></script>
</head>

<div class="general-container">
    <div class="graph-container">
        <svg id="graph">

        </svg>
    </div>
    <div class="func-container">
        <button id="cancel_button" class="func-button" onclick="cancel_button()" disabled>Cancel</button>
        <button class="func-button" onclick="clear_result()">Clear results</button>
        <div class="func-subtitle">Graph control</div>
        <button class="func-button" onclick="add_vertex()">Add vertex</button>
        <button class="func-button" onclick="add_connection(this)">Add connection</button>
        <button class="func-button" onclick="remove_vertex(this)">Remove vertex</button>
        <button class="func-button" onclick="remove_connection(this)">Remove connection</button>
        <button class="func-button" onclick="clear_graph()">Clear graph</button>
        <button class="func-button" onclick="" style="display:none">Save</button>
        <div class="func-subtitle">Graph info</div>
        <button class="func-button" onclick="adjacency_matrix_info()">Adjacency matrix</button>
        <button class="func-button" onclick="incidence_matrix_info()">Incidence matrix</button>
        <button class="func-button" onclick="weighted_matrix_info()">Weighted matrix</button>
        <button class="func-button" onclick="adjacency_lists_info()">Adjacency lists</button>
        <button class="func-button" onclick="edges_list_info()">Edges list</button>
        <div class="func-subtitle">Shortest path algorithms</div>
        <button class="func-button" onclick="dijkstra(this)">Dijkstra's algorithm</button>
        <button class="func-button" onclick="floyd()">Floyd's algorithm</button>
        <div class="func-subtitle">Search methods</div>
        <button class="func-button" onclick="depth_first_search(this)">Depth-first search</button>
        <button class="func-button" onclick="breadth_first_search(this)">Breadth-first search</button>
    </div>
</div>
<div class="status" id="status">
    <p><b>Welcome!</b></p>
</div>

src/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GraphCreator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />

    <!-- HTML Meta Tags -->
    <meta name="description" content="@ViewData["Description"]">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://graphcreator.azurewebsites.net">
    <meta property="og:type" content="website">
    <meta property="og:title" content="GraphCreator">
    <meta property="og:description" content="@ViewData["Description"]">
    <meta property="og:image" content=@Url.Content("~/images/previewImage.png")>

    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="graphcreator.azurewebsites.net">
    <meta property="twitter:url" content="https://graphcreator.azurewebsites.net">
    <meta name="twitter:title" content="GraphCreator">
    <meta name="twitter:description" content="@ViewData["Description"]">
    <meta name="twitter:image" content=@Url.Content("~/images/previewImage.png")>
    <!-- Meta Tags Generated via https://www.opengraph.xyz -->

    <meta name="google-site-verification" content="@ViewData["GoogleId"]" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Graph" asp-action="Index">GraphCreator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Graph" asp-action="Index">Graph</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GraphCreator
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>